apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: react-app
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: adewumi/reverse-proxy-frontend:latest
        ports:
        - containerPort: 3000
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 10001
        #   capabilities:
        #     drop:
        #       - all
        #   readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
      # nodeSelector:
      #   beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: frontend
  name: frontend
  namespace: react-app
spec:
  ports:
    - nodePort: 30018
      port: 3000
      targetPort: 3000
  selector:
    name: frontend
  type: LoadBalancer
